---
msbroker_namespace: managed-service-broker
msbroker_image_org: quay.io/btison
msbroker_image_tag: 0.0.2
msbroker_git_ref: gpte-rhpam-sso
msbroker_template_url: "https://raw.githubusercontent.com/gpte-integr8ly/managed-service-broker/{{ msbroker_git_ref }}/templates/broker.template.yaml"
msbroker_clusterrole: managed-service
msbroker_clusterrolebinding: default-cluster-account-managed-service
msbroker_deployment_name: msb
msbroker_servicebroker_name: managed-service-broker
monitoring_key: brokered-fuse-online
msbroker_fuse_operator_resources_url: https://raw.githubusercontent.com/syndesisio/fuse-online-install/{{fuse_online_release_tag}}/resources/fuse-online-operator.yml
required_crds:
  - "https://raw.githubusercontent.com/syndesisio/fuse-online-install/{{fuse_online_release_tag}}/resources/syndesis-crd.yml"
  - "https://raw.githubusercontent.com/gpte-integr8ly/rhpam-dev-operator/master/deploy/crds/rhpam_v1alpha1_rhpamdev_crd.yaml"
  - "https://raw.githubusercontent.com/gpte-integr8ly/rhpam-dev-operator/master/deploy/crds/rhpam_v1alpha1_rhpamuser_crd.yaml"  
